:sparkles: [#132] added api validation to check if nummeraanduiding_i…
maykinmedia/open-klant pull request #133
Opened 2024-01-11 09:13 UTC by bart-maykin

…d is given when gegevens groep is filled in

fixes #132 

added validation to gegevengroepen to see if nummeraanduiding_id must be required or not.

2024-01-17 08:33 UTC, joeribekker reviewed
@bart-maykin waar komt dit issue vandaan?

2024-01-17 08:52 UTC, joeribekker requested changes
Marking as request changes to make it clear to something is up :)

2024-01-17 12:07 UTC, bart-maykin commented
> @bart-maykin waar komt dit issue vandaan?

In het gegevenswoordenboek is het ID veld gemarkeerd als required. En omdat dit in een gegevens groep zit, is het logisch dat dit alleen het geval is als de gegevens groep ingevuld is. Maar de functionaliteit miste we nog dus daarom had ik deze issue aangemaakt.

![Screenshot from 2024-01-17 13-03-02](https://github.com/maykinmedia/open-klant/assets/101265650/bc9245e2-cb4e-4eff-bc05-659349531e0f)

2024-01-26 10:43 UTC, joeribekker commented
Zie ticket waarom gesloten.

2024-01-26 10:43 UTC, closed without merging