[#188] remove unused notification settings
maykinmedia/open-klant pull request #193
Opened 2024-06-07 09:56 UTC by Coperh

Fixes: #188

2024-06-07 12:26 UTC, stevenbal approved these changes

2024-06-07 12:28 UTC, stevenbal requested changes
I forgot about this, the pages for both the APIs still show links to the notification docs (which result in a 404), those should be deleted too

![image](https://github.com/maykinmedia/open-klant/assets/29249171/75e8796c-893d-4b43-ac0e-def1c7bcb477)

2024-06-07 13:56 UTC, Coperh commented
Remove, but is is displayed on top of each other if that matters. Its technically not docs
![Screenshot from 2024-06-07 15-55-50](https://github.com/maykinmedia/open-klant/assets/3464144/5bdca298-849a-48e5-a118-d42dd00a91a5)

2024-06-13 12:05 UTC, stevenbal commented
@Coperh seems fine to me to display them like that. I will create a separate issue to see what we need to do with the `Runtime behaviour` link though, because it links to documentation by VNG for v1 of the APIs (and also mentions that this is outdated), but I'm not sure if there's any VNG documentation for version 2 of the APIs

2024-06-13 12:17 UTC, stevenbal approved these changes

2024-06-17 07:22 UTC, merged