Feature/189 install maykin 2fa
maykinmedia/open-klant pull request #194
Opened 2024-06-07 12:17 UTC by Coperh

Fixes #189 

Depends on #190

2024-06-07 14:06 UTC, Coperh commented
Requires maykinmedia/open-api-framework#27 to be merged and released

2024-06-17 10:08 UTC, Coperh commented
Requires https://github.com/maykinmedia/open-api-framework/pull/31 to be merged and released.

2024-06-17 10:51 UTC, Coperh commented
Waiting for Other PRs to merge

2024-07-02 12:41 UTC, Coperh commented on src/openklant/accounts/tests/test_admin.py
> +    @tag("gh-4072")
Do we care enough to remove this tag?

2024-07-04 09:47 UTC, stevenbal requested changes
Works as expected, could you also add `DISABLE_2FA` to the docker-compose envvars (with default `True`)?

I do notice that some templates show the admin version though, these should not be visible until the user is fully authenticated

after adding 2FA:
![image](https://github.com/maykinmedia/open-klant/assets/29249171/2761b7ad-3075-468f-9794-580336f0bba6)
backuptokens template:
![image](https://github.com/maykinmedia/open-klant/assets/29249171/4cf1fb6d-e282-4425-a9a1-9658b0dacf60)

I think this can be fixed by overriding the base template footer: https://github.com/open-zaak/open-zaak/blob/main/src/openzaak/templates/maykin_2fa/base.html

2024-07-04 09:47 UTC, stevenbal commented on src/openklant/accounts/tests/test_admin.py
> +    @tag("gh-4072")
Hmm yeah, let's just remove it

2024-07-11 09:23 UTC, stevenbal approved these changes

2024-07-11 12:06 UTC, merged