Feature/233 fix values partij identificatoren
maykinmedia/open-klant pull request #291
Opened 2024-11-25 14:14 UTC by danielmursa-dev

Fixes #233

2024-12-24 13:17 UTC, stevenbal requested changes

2024-12-24 13:17 UTC, stevenbal commented on src/openklant/components/klantinteracties/models/validators.py
> +        ):
```suggestion
        if not self.code_soort_object_id in (choices := self.REGISTERS[self.code_register].get(self.code_objecttype, [])):
```

2024-12-24 13:17 UTC, stevenbal commented on src/openklant/components/klantinteracties/models/validators.py
> +                    )
```suggestion
                    "partij_identificator_code_soort_object_id": _(
                        "voor `codeObjecttype` {code_objecttype} zijn alleen deze waarden toegestaan: {choices}."
                    ).format(code_objecttype=self.code_objecttype, choices=choices)
```

2024-12-30 11:11 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/validators.py
> +            PartijIdentificatorCodeObjectType.overige: [],
is only by default to mean that it has nothing inside it

2024-12-30 11:13 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/validators.py
> +        self.validate_isdigit()
@stevenbal so you suggest to take it out of the model, and only use it in the class? my idea is to keep all validation in one place, so in the class

2024-12-30 14:20 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/validators.py
> +            raise ValidationError("Invalid code", code="invalid")
Right, this is the PR: https://github.com/maykinmedia/commonground-api-common/pull/58

2025-01-06 13:18 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/constants.py
> +    kvknummer = "kvknummer", _("KvkNummer")
OK, let's continue using the no-camelcase policy. `kvkNummer` becomes `kvk_nummer`

2025-01-15 13:38 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/validators.py
> +        },
Yes right, but it was for the case when the `register` was `overig`, to be able to continue in the third level, but I fixed it by creating a separate dict `ALLOWED_OBJECT_TYPES_FOR_CODE_OBJECTTYPE`

2025-01-15 13:41 UTC, danielmursa-dev commented on src/openklant/components/klantinteracties/models/partijen.py
>          blank=True,
Exactly, the initial specification allowed empty values, now with hierarchy/structure must be respected at every level

2025-01-16 13:49 UTC, stevenbal approved these changes
Looks good to me, just two questions about potential cleanup

2025-01-16 13:49 UTC, stevenbal commented on src/openklant/components/klantinteracties/models/validators.py
> +            PartijIdentificatorCodeObjectType.overig.value: [],
I'm not sure if `overig` needs to be here, since the methods below return early if register == `overig`

2025-01-16 13:49 UTC, stevenbal commented on src/openklant/components/klantinteracties/models/validators.py
> +            PartijIdentificatorCodeObjectType.natuurlijk_persoon.value: NATUURLIJK_PERSOON,
Do you need to map to the list of possible objecttype codes here? From what I can see in the code you use `.keys()`, so I think it can just be a list instead?

2025-01-17 14:55 UTC, merged