Feature/62 klantcontact
maykinmedia/open-klant pull request #74
Opened 2023-10-11 08:11 UTC by bart-maykin

Fixes #62 

Changed model structure
Added Klantcontact model

2023-10-11 08:17 UTC, bart-maykin commented
Needs to be merged after #61

2023-10-18 13:51 UTC, joeribekker requested changes

2023-10-18 13:51 UTC, joeribekker commented on src/openklant/components/klantinteracties/models/klantcontacten.py
> +        default=uuid.uuid4,
```suggestion
    uuid = models.UUIDField(
        unique=True,
        default=uuid.uuid4,
```

2023-10-18 13:51 UTC, joeribekker commented on src/openklant/components/klantinteracties/models/klantcontacten.py
> +    taal = models.CharField(
zelfde als partij opmerking. Pas wel even de helptekst aan zodat het nog klopt.

2023-10-18 13:51 UTC, joeribekker commented on src/openklant/components/klantinteracties/models/klantcontacten.py
> +    plaatsgevonden_op = models.DateTimeField(
je mag hier een default op zetten: default=timezone.now (zie django docs).

2023-10-19 13:55 UTC, closed without merging