Feature/63 betrokkene bij klantcontact
maykinmedia/open-klant pull request #75
Opened 2023-10-11 10:46 UTC by bart-maykin

Fixes #63 

Added betrokkene model

2023-10-11 10:46 UTC, bart-maykin commented
#62 needs to be merged first.

2023-10-18 13:55 UTC, joeribekker requested changes
Zelfde algemene punten

2023-10-18 13:55 UTC, joeribekker commented on src/openklant/components/klantinteracties/models/klantcontacten.py
> +        null=False,
```suggestion
```

niet nodig, is de default :)

2023-10-18 13:55 UTC, joeribekker commented on src/openklant/components/klantinteracties/models/klantcontacten.py
> +    correspondentieadres_nummeraanduiding_id = models.UUIDField(
Dit wordt je mixin? Zelfde opmerkingen als bij partij.

2023-10-19 13:55 UTC, closed without merging